Bmes/Models/Cart/Cart.cs
namespace Bmes.Models.Cart
{
    using Shared;
    using System.Collections.Generic;

    public class Cart : BaseObject
    {
        public Cart()
        {
            CartItems = new List<CartItem>();
        }

        public string UniqueCartId { get; set; }
        public CartStatus CartStatus { get; set; }
        public IEnumerable<CartItem> CartItems { get; set; }
    }
}

Bmes/Models/Cart/CartItem.cs
namespace Bmes.Models.Cart
{
    using Shared;
    using Product;
    public class CartItem : BaseObject
    {
        public long CartId { get; set; }
        public Cart Cart { get; set; }
        public long ProductId { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

Bmes/Models/Cart/CartStatus.cs
namespace Bmes.Models.Cart
{
    public enum CartStatus
    {
        Open = 0,
        CheckedOut = 1
    }
}

Bmes/ViewModels/Cart/AddToCartViewModel.cs
namespace Bmes.ViewModels.Cart
{
    public class AddToCartViewModel
    {
        public long ProductId { get; set; }

        public string CategorySlug { get; set; }
        public string BrandSlug { get; set; }
        public string Page { get; set; }
    }
}

Bmes/ViewModels/Cart/RemoveFromCartViewModel.cs
namespace Bmes.ViewModels.Cart
{
    public class RemoveFromCartViewModel
    {
        public long CartItemId { get; set; }
    }
}

Bmes/Controllers/CartController.cs
using Bmes.Services;
using Bmes.ViewModels.Cart;
using Microsoft.AspNetCore.Mvc;

namespace Bmes.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;

        public CartController(ICartService cartService)
        {
            _cartService = cartService;
        }

        [HttpGet]
        public IActionResult CartDetail()
        {
            ViewData["CartTotal"] = _cartService.GetCartTotal();
            ViewData["CartItemsCount"] = _cartService.CartItemsCount();
            ViewData["CartItems"] = _cartService.GetCartItems();

            return View();
        }

        [HttpPost]
        public IActionResult RemoveCartItem(RemoveFromCartViewModel removeFromCartViewModel)
        {
            _cartService.RemoveFromCart(removeFromCartViewModel);
            return RedirectToAction("CartDetail");
        }

        [HttpPost]
        public IActionResult AddItemToCart(AddToCartViewModel addToCartViewModel)
        {
           _cartService.AddToCart(addToCartViewModel);


           if (addToCartViewModel.CategorySlug == "all-categories" && addToCartViewModel.BrandSlug == "all-brands")
           {
               return RedirectToAction("Index", "Catalogue", new { category_slug = "", brand_slug = "", page = addToCartViewModel.Page == "1" ? null : addToCartViewModel.Page });
           }
           else
           {
               return RedirectToAction("Index", "Catalogue", new { category_slug = addToCartViewModel.CategorySlug, brand_slug = addToCartViewModel.BrandSlug, page = addToCartViewModel.Page == "1" ? null : addToCartViewModel.Page });
           }
           
        }
    }
}

Bmes/Controllers/CheckoutController.cs
using Bmes.Services;
using Bmes.ViewModels.Checkout;
using Microsoft.AspNetCore.Mvc;

namespace Bmes.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly ICheckoutService _checkoutService;
        private readonly ICartService _cartService;
        public CheckoutController(ICheckoutService checkoutService, ICartService cartService)
        {
            _checkoutService = checkoutService;
            _cartService = cartService;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            ViewData["CartTotal"] = _cartService.GetCartTotal();
            ViewData["CartItemsCount"] = _cartService.CartItemsCount();
            ViewData["CartItems"] = _cartService.GetCartItems();

            return View();
        }

        [HttpPost]
        public IActionResult Checkout(CheckoutViewModel checkoutViewModel)
        {
            _checkoutService.ProcessCheckout(checkoutViewModel);

            return RedirectToAction("Receipt");
        }

        public IActionResult Receipt()
        {
            return View();
        }
    }
}

Bmes/Views/Cart/CartDetail.cshtml
@{
  ViewData["Title"] = "Cart Detail";
  var cartTotal = Convert.ToDecimal(ViewData["CartTotal"]);
  var cartItemsCount = Convert.ToInt32(ViewData["CartItemsCount"]);
  var cartItems = ViewData["CartItems"] as IEnumerable<CartItem>;
  var removeFromCartViewModel = new RemoveFromCartViewModel();
}


<div class="container cart_detail">
  <div class="row no-gutters display-flex cart_detail__row">
    <div class="col-md-9 cart_detail__cart-panel">
      <div class="cart_detail__cart-panel-header">
        <div class="cart_detail__cart-panel-title ">
          <p>Your Cart</p>
        </div>
        <div>
          <a href="/" class="cart_detail__continue-shopping-button">Continue Shopping</a>
        </div>
      </div>
      <div>
        <table class="table table-bordered table-striped">
          <thead class="cart_detail__table-head">
            <tr>
              <th class="cart_detail__table-head-item">Item</th>
              <th></th>
              <th class="text-center cart_detail__table-head-item">Price</th>
              <th class="text-center cart_detail__table-head-item">Quantity</th>
              <th class="text-center cart_detail__table-head-item">Total</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            @foreach (var item in cartItems)
            {
              <tr class="cart_detail__table-body-item-wrapper">
                <td class="text-center">
                  <img src="/images/productimages/main/@item.Product.ImageUrl" class="cart_detail__image" />
                </td>
                <td class="text-left cart_detail__table-body-item-name">@item.Product.Name</td>
                <td class="text-center cart_detail__table-body-item-price">$@item.Product.Price</td>
                <td class="text-center cart_detail__table-body-item-quantity">@item.Quantity</td>
                <td class="text-center cart_detail__table-body-item-total">$@(item.Quantity * item.Product.Price)</td>
                <td class="text-center">
                  <form asp-controller="Cart" asp-action="RemoveCartItem" method="post">
                    <input type="hidden" asp-for="@removeFromCartViewModel.CartItemId" name="CartItemId" value="@item.Id" />
                    <button type="submit" class="cart_detail__table-remove-button">X</button>
                  </form>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-3 cart_detail__summary-panel">
      <div class="cart_detail__summary-panel-title-wrapper">
        <p class="cart_detail__summary-panel-title">Cart Summary</p>
      </div>
      <div class="cart_detail__summary-panel-total">
        <span class="cart_detail__summary-panel-total-title">Items(@cartItemsCount)</span>
        <span>$@cartTotal</span>
      </div>
      <div class="cart_detail__summary-panel-ads">
        <p class="cart_detail__summary-panel-ads-lable">Free 3-Day Shipping!</p>
      </div>
      <div style="margin-top: 25px;">
        <a asp-controller="Checkout" asp-action="Checkout" class="cart_detail__summary-panel-checkout-button">PROCEED TO CHECKOUT</a>
      </div>
    </div>
  </div>
</div>